[tool.poetry]
name = "epsilonhacksproject"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3"
pymongo = "^3.10"
dnspython = "^1.16"
bcrypt = "^3.1"
flask-login = "^0.5.0"
flask-socketio = "^4.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
